[project]
name = "svg-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cairosvg>=2.9.0",
    "deepagents>=0.5.7",
    "google-genai>=1.75.0",
    "groq>=1.1.2",
    "langchain>=1.2.17",
    "langchain-openrouter>=0.2.3",
    "langgraph>=1.1.10",
    "lxml>=6.0.4",
    "pillow>=12.2.0",
    "pyqt6>=6.11.0",
    "python-dotenv>=1.2.2",
    "svgwrite>=1.4.3",
]
